global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'shreyasghanekar35@gmail.com'
  smtp_auth_username: 'shreyasghanekar35@gmail.com'
  smtp_auth_password: 'your-app-password'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'team-notifications'

receivers:
- name: 'team-notifications'
  email_configs:
  - to: 'shreyasghanekar35@gmail.com.com'
    send_resolved: true
  # slack_configs:
  # - api_url: 'https://hooks.slack.com/services/your/slack/webhook'
  #   channel: '#alerts'
  #   send_resolved: true