version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - postgres
    environment:
      - B2_KEY_ID=your-key-id
      - B2_APPLICATION_KEY=your-application-key
      - B2_BUCKET_NAME=your-bucket-name
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=log_system
    ports:
      - "5432:5432"
  fluentd:
    build: ./fluentd
    volumes:
      - ./backend/logs:/logs
    depends_on:
      - mongo
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
  alertmanager:
    build: ./prometheus
    ports:
      - "9093:9093"
  node-exporter:
    image: prom/node-exporter:v1.5.0
    ports:
      - "9100:9100"