global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'shreyasghanekar35@gmail.com'
  smtp_auth_username: 'shreyasghanekar35@gmail.com'
  smtp_auth_password: 'your-app-password'
route:
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - to: 'shreyasghanekar35@gmail.com'