name: CI/CD
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push backend
      run: |
        cd backend
        docker build -t your-dockerhub/backend:latest .
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push your-dockerhub/backend:latest
    - name: Build and push frontend
      run: |
        cd frontend
        docker build -t your-dockerhub/frontend:latest .
        docker push your-dockerhub/frontend:latest
    - name: Build and push fluentd
      run: |
        cd fluentd
        docker build -t your-dockerhub/fluentd:latest .
        docker push your-dockerhub/fluentd:latest
    - name: Build and push prometheus
      run: |
        cd prometheus
        docker build -t your-dockerhub/prometheus:latest -f Dockerfile .
        docker build -t your-dockerhub/alertmanager:latest -f alertmanager.Dockerfile .
        docker push your-dockerhub/prometheus:latest
        docker push your-dockerhub/alertmanager:latest
    - name: Deploy to EKS
      uses: aws-actions/amazon-eks@v1
      with:
        cluster-name: log-aggregation-system
        kubeconfig: ${{ secrets.KUBECONFIG }}
      run: kubectl apply -f k8s/deployment.yaml